### ISSUE TITLE
L1 South Dome spikes [and tower leaning?]

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing#98] opened 2023-01-05 16:08 UTC
I spent an hour trying to resolve dates when the imprecise definition of HS1 and HS2 is causing spikes and various offsets of 1+ m.

Here are my rough (not to the closest hour) fixes that contain offset dates for GC-Net-level-1-data-processing/L1/11-SouthDome.csv

'''
        if nicknames[0]=='SDM':
            t=datetime(1998, 4, 18)
            df['HS1'][t:]-=0.2
            df['HS2'][t:]-=0.2
            t=datetime(1999, 4, 22)
            df['HS1'][t:]-=0.5
            df['HS2'][t:]-=0.5
            t=datetime(2006, 7, 17)
            df['HS1'][t:]-=0.4
            t=datetime(2009, 1, 1)
            df['HS2'][t:]+=0.51
            t=datetime(2011, 5, 28)
            df['HS2'][t:]-=2.9
            df['HS1'][t:]+=3.04
            t=datetime(2013, 5, 20)
            df['HS1'][t:]-=2.25
            df['HS2'][t:]-=0.25
            t=datetime(2015, 4, 30)
            df['HS2'][t:]-=3
            t=datetime(2015, 5, 24)
            df['HS2'][t:]+=2.48
            t=datetime(2018, 10, 24)
            value=0.4
            df['HS1'][t:]-=value
            df['HS2'][t:]-=value
            t=datetime(2019, 4, 24)
            df['HS1'][t:]+=2.1
            df['HS2'][t:]+=2.15
'''

the above rough fixes remove most of the offsets so far. But the issue I think I see is SDM tower leaning May 2007 (or is it real snow deflation)? in this image. The decrease in HS is too great for so early in the season? Anyway, I'll share more offsets may be as editing this issue.

![image](https://user-images.githubusercontent.com/32133350/210825773-674dc281-34ca-45dc-ba9e-5d3347681f99.png)

now the adjusted full series looks like the following. However, I'm not very confident I didn't neutralise real trends, especially when there are gaps. To gain confidence about whether or not there are gaps, it may help to obtain from notes e.g. the length of mast inserts. Better may be if other info like from photogrammetry could help resolve the actual offsets from tower mast extension. L0 data may be the ultimate way to resolve the uncertainty I've introduced here?

![image](https://user-images.githubusercontent.com/32133350/210848882-921fb5f4-9765-41dc-b9bb-aaa81cc54b29.png)

**Comment by BaptisteVandecrux** [comment] 2023-01-06 15:32
The spikes were due to:
1) inaccurate time for manual shift
2) the gap-filling (interpolation) of gaps instrument heights prior to surface height reconstruction leading to strange ramps
3) some typo in the existing shifts

This should be fixed now.

Also please note that the shift applied across a data gap is just meant to reproduce the general linear trend of the surface height increase. It should not be used to derive accumulation during the data gap.

An example here. The gaps in early 2007 and 2009 ends with a maintenance, therefore no accumulation estimate can be made over those gaps (at least not directly from the observations). The smaller gaps at the end of 2010 are not connected to maintenance, and therefore the height change during the gap can be used to derive accumulation over that period. 

![image](https://user-images.githubusercontent.com/35140661/211042932-bbd60812-d1a6-4fb4-9f89-1f12e48df745.png)

Leaning tower is not currently accounted for in the dataset.
We are missing measurements of station tilt from pictures and field notes.
Should be opened as a separate issue.

**Closed** 2023-01-06 15:33 UTC
